### ISSUE TITLE
ld2412

### ISSUE THREAD

**Issue by Richard-Lemon** [iavorvel/MyLD2410#1]
Hello, friends! Recently, HLK has used this library in addition to a new LD2410-like sensor LD2412, but it doesn't seem to work, if possible, can you help me adapt it? Thank you so much!Here's the documentation for it！
[HLK-LD2412 Serial Communication Protocol.pdf](https://github.com/user-attachments/files/16709960/HLK-LD2412.Serial.Communication.Protocol.pdf)

**Comment by iavorvel** [comment]
LD2412 seems to be a very different sensor. MyLD2410 library only works with LD2410x sensors (see the instructions)
I could in principle write a separate library for the LD2412 sensor if I had one to test...

**Comment by Richard-Lemon** [comment]
您的邮件已收到！

**Comment by Richard-Lemon** [comment]
hank you for your reply, I observed that the documentation for these two sensors is not very different, maybe I can modify it on the basis of your library, I will try it. Thank you

**Comment by iavorvel** [comment]
Sure. The first step is to change the default baud rate to 115200. The serial communication protocol is the same; you will need to introduce several new commands, though.

**Comment by Richard-Lemon** [comment]
Yes, the baud rate is different, it seems that most of the instructions are the same, a few new instructions need to be added, the basic framework is the same, I will try it

**Comment by iavorvel** [comment]
For now the library only supports LD2410x. 
In the future, I may introduce the LD2412-specific commands when I get my hands on that sensor for testing
