### ISSUE TITLE
Crashes when status isn't an expected value

### ISSUE THREAD

**Issue by glychee** [iavorvel/MyLD2410#2]
I've gotten a LD2410C and connected it to my Arduino Micro, this library works great and the debug mode is awesome. 

in my case sometimes a package is produced that has a status value of 131 (I don't know why) and translating this to tStatus enum and printing it to serial will crash the whole serial communication and freeze up the microcontroller. I have a PN532 NFC scanner connected on I2C and they share the power line, so perhaps the dips in power cause the faulty package. 

In my case I ended up fixing my situation it by not using the statusString() function and just using the getStatus() function, then matching against enum value for moving targets, as that's the only one I'm interested in..

It's possible to build in protection for situations such as these by  updating either the getStatus() function or the statusString() function to ensure access to the enum is legal(fits in size?), but I'm not sure if my case is an outlier or the norm, due to me only having the one setup.

**Comment by iavorvel** [comment]
Thank you for discovering this bug. 
The status byte, per the documentation, can only take values between 0 and 3. In a rare case like yours, a bit may get flipped resulting in a status outside of this range. 
131 = b10000011 -> bit 7 must be 0, but was received as 1. 
I fixed this bug in line 209 of MyLD2410.cpp:
sData.status = inBuf[2] & 3;

I will be publishing v1.0.7 later today.

**Comment by iavorvel** [comment]
V1.0.7 fixes this bug
